sonar.projectKey=markupai_vscode-extension
sonar.organization=markupai
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.coverage.exclusions=test/**,src/extension.ts,src/views/**/webview.html.ts,**/*.mjs
sonar.cpd.exclusions=test/**,src/views/**/webview.html.ts
